models/users.py
from flask_login import UserMixin

class User(UserMixin):
    def __init__(self, **kwargs):
        self.email = kwargs.get("email")
        self.password = kwargs.get("password")
        self.id = kwargs.get("id")

views/accounts.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, login_user, logout_user , current_user
from werkzeug.utils import secure_filename
from werkzeug.security import generate_password_hash , check_password_hash
import os

from forms import accountslog as accounts_form
from forms import registerweb as regester_form
from forms import addport as addport_form
from forms import editport as editport_form
from models import users
from models.database import user
from models.database import port

UPLOAD_FOLDERMy = 'static/img'
UPLOAD_FOLDERPort = 'static/img_port'
ALLOWED_EXTENSIONS = {'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'}


bp = Blueprint("user",__name__,"/users")

user_login = user()

@bp.route("/register")
def register():
    user_db = user()
    try:
        current_user_in = user_db.find_one({"id":current_user.id})
        current_user_in = current_user_in["name"]
    except:current_user_in = "please login"
    form = regester_form.RegisterForm()
    return render_template("/users/register.html",form=form,current_user_in=current_user_in)

@bp.route("/do-register" , methods = ["POST"])
def do_register():
    user_db = user()
    try:
        current_user_in = user_db.find_one({"id":current_user.id})
        current_user_in = current_user_in["name"]
    except:current_user_in = "please login"
    form = regester_form.RegisterForm()
    userlog = user()
    if userlog.find_one({"email":form.email.data}):
        return redirect(url_for("user.register", message="email is used"))
    if not form.validate_on_submit():
        return redirect(url_for("user.register", **form.errors))
    password = generate_password_hash(form.password.data)
    userlog.insert_one({"name":form.name.data,"email":form.email.data,"password":password,"id":form.name.data+form.email.data})
    return render_template("/users/regispass.html",current_user_in=current_user_in)

@bp.route("/login")
def login():
    user_db = user()
    try:
        current_user_in = user_db.find_one({"id":current_user.id})
        current_user_in = current_user_in["name"]
    except:current_user_in = "please login"
    form = accounts_form.LoginForm()
    return render_template("/users/login.html", form=form,current_user_in=current_user_in)

@bp.route("/do-login", methods=["POST"])
def do_login():
    
    # email = request.form.get("email")
    # password = request.form.get("password")

    # print("-->", email, password)
    # print(request.form)


    form = accounts_form.LoginForm()

    if not form.validate_on_submit():
        return redirect(url_for("user.login", **form.errors))

    user_data = user_login.find_one({"email":form.email.data})

    if not user_data:
        return redirect(url_for("user.login", message = "invalid email"))

    if not check_password_hash(user_data["password"],form.password.data):
        return redirect(url_for("user.login", message="invalid password"))

    #user_data = None
    #for id, u in database["users"].items():
    #    if u.get("email") == form.email.data:
    #        user_data = u

    #if not (u and form.password.data == u.get("password")):
    #    return redirect(url_for("user.login", message="invalid login"))

    user = users.User(**user_data)
    login_user(user)

    print(user)
    print(user.__dict__)

    return redirect(url_for("user.list_edit"))

@bp.route("/logout")
def logout():
    logout_user()
    return redirect("/")

@bp.route("/add")
@login_required
def add():
    user_db = user()
    try:
        current_user_in = user_db.find_one({"id":current_user.id})
        current_user_in = current_user_in["name"]
    except:current_user_in = "please login"
    form = addport_form.AddForm()
    return render_template("/users/add.html",form = form,current_user_in=current_user_in)

@bp.route("/do-add" , methods = ["POST"])
@login_required
def do_add():
    form = addport_form.AddForm()

    #bp.config['UPLOAD_FOLDER'] = UPLOAD_FOLDERMy
    profile = request.files['photomy']
    path_save_myphoto = ''
    if profile:
        profile_name = secure_filename(profile.filename)
        path_save_myphoto = os.path.join(UPLOAD_FOLDERMy, profile_name)
        profile.save(path_save_myphoto)

    #bp.config['UPLOAD_FOLDER'] = UPLOAD_FOLDERPort
    profile = request.files['photoperformance']
    path_save_profile = ""
    if profile:
        profile_name = secure_filename(profile.filename)
        path_save_profile = os.path.join(UPLOAD_FOLDERPort, profile_name)
        profile.save(path_save_profile)

    all_port = port()
    list_myport = all_port.find({"user_id":current_user.id})
    print("port_id ==> ",list_myport)
    list_myport = list(list_myport)
    if  len(list_myport) != 0:
        number_myport = list_myport[-1]
        number_myport = number_myport["port_id"] + 1
    else:
        number_myport = 0

    add_port = port()
    add_port.insert_one({   
                            "photomy":path_save_myphoto,
                            "fname":form.fname.data,
                            "lname":form.lname.data,
                            "email":form.email.data,
                            "road":form.road.data,
                            "tambon":form.tambon.data,
                            "amphor":form.amphor.data,
                            "city":form.city.data,
                            "zip_code":form.zip_code.data,
                            "tel":form.tel.data,
                            "skill":form.skill.data,
                            "performance":form.performance.data,
                            "photoperformance":path_save_profile,
                            "linkedin":form.linkedin.data,
                            "github":form.github.data,
                            "twitter":form.twitter.data,
                            "facebook":form.facebook.data,
                            "user_id":current_user.id,
                            "port_id":number_myport,
                            "user_port_id":current_user.id+str(number_myport)
                            
                        })
    return redirect(url_for('user.list_edit'))

@bp.route("/edit")
@login_required
def edit():
    user_db = user()
    try:
        current_user_in = user_db.find_one({"id":current_user.id})
        current_user_in = current_user_in["name"]
    except:current_user_in = "please login"
    return render_template("/users/edit.html",current_user_in=current_user_in)

@bp.route("/list_edit")
@login_required
def list_edit():
    user_db = user()
    try:
        current_user_in = user_db.find_one({"id":current_user.id})
        current_user_in = current_user_in["name"]
    except:current_user_in = "please login"
    load_users = current_user.id
    print("id => ",load_users)
    all_port = port()
    list_port = all_port.find({"user_id":load_users})
    list_port = list(list_port)
    l = len(list_port)
    data = [list_port[i:i+3] for i in [3*(ip) for ip in range((l//3))]]
    ll = len(data)
    if not ll*3 == l:
        data.append(list_port[ll*3:])
    #data.append(l%3)
    return render_template("/users/listmyport.html",datas = data,current_user_in=current_user_in)

@bp.route("/form-edit/<port_ids>" , methods = ["GET","POST"])
@login_required
def form_edit(port_ids):
    user_db = user()
    try:
        current_user_in = user_db.find_one({"id":current_user.id})
        current_user_in = current_user_in["name"]
    except:current_user_in = "please login"
    all_port = port()
    form = editport_form.EditForm()
    user_port_id = current_user.id + port_ids
    data_myport = all_port.find_one({"user_port_id":user_port_id})
    return render_template("/users/edit.html",form = form,datas = data_myport,current_user_in=current_user_in)

@bp.route("/do-edit" , methods = ["POST"])
@login_required
def do_edit():
    form = editport_form.EditForm()
    user_port_id = form.user_port_id.data
    print("===>",user_port_id)

    all_port = port()
    data_myport = all_port.find_one({"user_port_id":user_port_id})

    #bp.config['UPLOAD_FOLDER'] = UPLOAD_FOLDERMy
    
    if request.method == 'POST':
        profile = request.files['photomy']
    if profile:
        profile_name = secure_filename(profile.filename)
        path_save_myphoto = os.path.join(UPLOAD_FOLDERMy, profile_name)
        profile.save(path_save_myphoto)
        path_photomy = path_save_myphoto
    else:
        path_photomy = data_myport["photomy"]

    #bp.config['UPLOAD_FOLDER'] = UPLOAD_FOLDERPort
    performance = request.files['photoperformance']
    if performance:
        profile_name = secure_filename(performance.filename)
        path_save_profile = os.path.join(UPLOAD_FOLDERPort, profile_name)
        performance.save(path_save_profile)
        path_photoperformance = path_save_profile
    else:
        path_photoperformance = data_myport["photoperformance"]

    add_port = port()
    myquery = {"user_port_id":user_port_id}
    data_update = { "$set":{
                            "photomy":path_photomy,
                            "fname":form.fname.data,
                            "lname":form.lname.data,
                            "email":form.email.data,
                            "road":form.road.data,
                            "tambon":form.tambon.data,
                            "amphor":form.amphor.data,
                            "city":form.city.data,
                            "zip_code":form.zip_code.data,
                            "tel":form.tel.data,
                            "skill":form.skill.data,
                            "performance":form.performance.data,
                            "photoperformance":path_photoperformance,
                            "linkedin":form.linkedin.data,
                            "github":form.github.data,
                            "twitter":form.twitter.data,
                            "facebook":form.facebook.data,
                            "user_id":current_user.id,

templates/users/add.html
{%extends "layout.html"%}
{%block content%}
<div class="container text-center d-flex justify-content-around" style="margin-top: 2%;">
<form action="{{url_for('user.do_add')}}"  method="POST" enctype="multipart/form-data">
    <div class="form-group row">
      <label for="exampleFormControlFile1" class="col-sm-1 col-form-label">Photo</label>
      <div class="col-3">
      <input type="file" class="form-control-file" id="exampleFormControlFile1" name="photomy" multiple/>
    </div>
    </div>
    <br>
    <div class="form-group row">
        <label for="inputEmail3" class="col-sm-1 col-form-label">ชื่อ</label>
        <div class="col-3">
          <input type="text" class="form-control" id="inputEmail3" placeholder="ชื่อ" name="fname">
        </div>
        <label for="inputEmail3" class="col-sm-1 col-form-label">นามสกุล</label>
        <div class="col-3">
          <input type="text" class="form-control" id="inputEmail3" placeholder="นามสกุล" name="lname">
        </div>
    </div>
    <br>
      <div class="form-group row">
        <label for="inputEmail3" class="col-sm-1 col-form-label">Email</label>
        <div class="col-sm-3">
          <input type="email" class="form-control" id="inputEmail3" placeholder="Email" name="email">
        </div>
      </div>
      <br>
      <div class="form-group row">
        <label for="inputEmail3" class="col-sm-1 col-form-label">ซอย/ถนน</label>
        <div class="col-3">
          <input type="text" class="form-control" placeholder="ซอย/ถนน" name="road">
        </div>
        <label for="inputEmail3" class="col-sm-1 col-form-label">ตำบล</label>
        <div class="col-3">
          <input type="text" class="form-control" placeholder="ตำบล" name="tambon">
        </div>
        <label for="inputEmail3" class="col-sm-1 col-form-label">อำเภอ</label>
        <div class="col-3">
          <input type="text" class="form-control" placeholder="อำเภอ" name="amphor">
        </div>
      </div>
      <br>
      <div class="form-group row">
        <label for="inputEmail3" class="col-sm-1 col-form-label">จังหวัด</label>
        <div class="col-3">
          <input type="text" class="form-control" placeholder="จังหวัด" name="city">
        </div>
        <label for="inputEmail3" class="col-sm-1 col-form-label">รหัสไปรษณี</label>
        <div class="col-3">
          <input type="text" class="form-control" placeholder="รหัสไปรษณี" name="zip_code">
        </div>
        <label for="inputEmail3" class="col-sm-1 col-form-label">เบอร์โทร</label>
        <div class="col-3">
          <input type="text" class="form-control" placeholder="เบอร์โทร" name="tel">
        </div>
      </div>
      <br>
      <div class="form-group row">
        <label for="inputEmail3" class="col-sm-1 col-form-label">ทักษะ/ความสามารถพิเศษ</label>
        <div class="col-sm-7">
          <textarea type="text" class="form-control" id="inputEmail3" placeholder="ทักษะ/ความสามารถพิเศษ" name="skill"></textarea>
        </div>
      </div>
      <br>
      <div class="form-group row">
        <label for="inputEmail3" class="col-sm-1 col-form-label">ผลงาน</label>
        <div class="col-sm-7">
          <textarea type="text" class="form-control" id="inputEmail3" placeholder="ผลงาน" name="performance"></textarea>
        </div>
      </div>
      <br>
      <div class="form-group row">
        <label for="exampleFormControlFile1" class="col-sm-1 col-form-label">รูปผลงาน</label>
        <div class="col-3">
        <input type="file" class="form-control-file" id="exampleFormControlFile1" name = "photoperformance" multiple/>
      </div>
      </div>
      <br>
      <div class="form-group row">
        <label for="inputEmail3" class="col-sm-1 col-form-label">linkedin</label>
        <div class="col-3">
          <input type="text" class="form-control" placeholder="link" name="linkedin">
        </div>
        <label for="inputEmail3" class="col-sm-1 col-form-label">github</label>
        <div class="col-3">
          <input type="text" class="form-control" placeholder="link" name="github">
        </div>
        <label for="inputEmail3" class="col-sm-1 col-form-label">twitter</label>
        <div class="col-3">
          <input type="text" class="form-control" placeholder="link" name="twitter">
        </div>
      </div>
      <br>
      <div class="form-group row">
        <label for="inputEmail3" class="col-sm-1 col-form-label">facebook</label>
        <div class="col-3">
          <input type="text" class="form-control" placeholder="link" name="facebook">
        </div>
      </div>
      <br>
      <button class="w-100 btn btn-lg btn-primary" type="submit">Upload</button>
  </form>
</div>
{%endblock%}

templates/users/edit.html
{%extends "layout.html"%}
{%block content%}
<div class="container text-center d-flex justify-content-around" style="margin-top: 2%;">
<form action="{{url_for('user.do_edit')}}" method="POST" enctype="multipart/form-data">
    <input type="hidden" id="custId" name="user_port_id" value={{datas.user_port_id}}>
    <div class="form-group row">
      <label for="exampleFormControlFile1" class="col-sm-1 col-form-label">Photo</label>
      <div class="col-3">
      <input type="file" class="form-control-file" id="exampleFormControlFile1" name="photomy" multiple/>
      <img src="/{{datas.photomy}}" height="250">
    </div>
    </div>
    <br>
    <div class="form-group row">
        <label for="inputEmail3" class="col-sm-1 col-form-label">ชื่อ</label>
        <div class="col-3">
          <input type="text" class="form-control" id="inputEmail3" placeholder="ชื่อ" name="fname" value={{datas.fname}}>
        </div>
        <label for="inputEmail3" class="col-sm-1 col-form-label">นามสกุล</label>
        <div class="col-3">
          <input type="text" class="form-control" id="inputEmail3" placeholder="นามสกุล" name="lname" value="{{datas.lname}}">
        </div>
    </div>
    <br>
      <div class="form-group row">
        <label for="inputEmail3" class="col-sm-1 col-form-label">Email</label>
        <div class="col-sm-3">
          <input type="email" class="form-control" id="inputEmail3" placeholder="Email" name="email" value="{{datas.email}}">
        </div>
      </div>
      <br>
      <div class="form-group row">
        <label for="inputEmail3" class="col-sm-1 col-form-label">ซอย/ถนน</label>
        <div class="col-3">
          <input type="text" class="form-control" placeholder="ซอย/ถนน" name="road" value="{{datas.road}}">
        </div>
        <label for="inputEmail3" class="col-sm-1 col-form-label">ตำบล</label>
        <div class="col-3">
          <input type="text" class="form-control" placeholder="ตำบล" name="tambon" value="{{datas.tambon}}">
        </div>
        <label for="inputEmail3" class="col-sm-1 col-form-label">อำเภอ</label>
        <div class="col-3">
          <input type="text" class="form-control" placeholder="อำเภอ" name="amphor" value="{{datas.amphor}}">
        </div>
      </div>
      <br>
      <div class="form-group row">
        <label for="inputEmail3" class="col-sm-1 col-form-label">จังหวัด</label>
        <div class="col-3">
          <input type="text" class="form-control" placeholder="จังหวัด" name="city" value="{{datas.city}}">
        </div>
        <label for="inputEmail3" class="col-sm-1 col-form-label">รหัสไปรษณี</label>
        <div class="col-3">
          <input type="text" class="form-control" placeholder="รหัสไปรษณี" name="zip_code" value="{{datas.zip_code}}">
        </div>
        <label for="inputEmail3" class="col-sm-1 col-form-label">เบอร์โทร</label>
        <div class="col-3">
          <input type="text" class="form-control" placeholder="เบอร์โทร" name="tel" value="{{datas.tel}}">
        </div>
      </div>
      <br>
      <div class="form-group row">
        <label for="inputEmail3" class="col-sm-1 col-form-label">ทักษะ/ความสามารถพิเศษ</label>
        <div class="col-sm-7">
          <textarea type="text" class="form-control" id="inputEmail3" placeholder="ทักษะ/ความสามารถพิเศษ" name="skill">{{datas.skill}}</textarea>
        </div>
      </div>
      <br>
      <div class="form-group row">
        <label for="inputEmail3" class="col-sm-1 col-form-label">ผลงาน</label>
        <div class="col-sm-7">
          <textarea type="text" class="form-control" id="inputEmail3" placeholder="ผลงาน" name="performance">{{datas.performance}}</textarea>
        </div>
      </div>
      <br>
      <div class="form-group row">
        <label for="exampleFormControlFile1" class="col-sm-1 col-form-label">รูปผลงาน</label>
        <div class="col-3">
        <input type="file" class="form-control-file" id="exampleFormControlFile1" name = "photoperformance" value="{{datas.photoperformance}}" multiple/>
        <img src="/{{datas.photoperformance}}" height="250">
      </div>
      </div>
      <br>
      <div class="form-group row">
        <label for="inputEmail3" class="col-sm-1 col-form-label">linkedin</label>
        <div class="col-3">
          <input type="text" class="form-control" placeholder="link" name="linkedin" value="{{datas.linkedin}}">
        </div>
        <label for="inputEmail3" class="col-sm-1 col-form-label">github</label>
        <div class="col-3">
          <input type="text" class="form-control" placeholder="link" name="github" value="{{datas.github}}">
        </div>
        <label for="inputEmail3" class="col-sm-1 col-form-label">twitter</label>
        <div class="col-3">
          <input type="text" class="form-control" placeholder="link" name="twitter" value="{{datas.twitter}}">
        </div>
      </div>
      <br>
      <div class="form-group row">
        <label for="inputEmail3" class="col-sm-1 col-form-label">facebook</label>
        <div class="col-3">
          <input type="text" class="form-control" placeholder="link" name="facebook" value="{{datas.facebook}}">
        </div>
      </div>
      <br>
      <div class="form-group row" style="position: relative;left: 50%;">
        <div class="col-3">
            <button class="w-100 btn btn-lg btn-primary" type="submit">Save</button>   
        </div>
        <div class="col-3">
            <a href="{{url_for('user.delete',user_port_id = datas.user_port_id)}}" class="w-100 btn btn-lg btn-primary">Delete</a>
        </div>
      </div>
  </form>
</div>
{%endblock%}

templates/users/listmyport.html
{%extends "layout.html"%}
{%block content%}
<div class="container text-center" style="margin-top: 3%;">
  <div class="rounded" style="margin-bottom: 3%;font-size: 1.5cm;background-color: coral;">My Port</div>    
  {%for i in datas%}
    <div class="row" style="margin-bottom: 5%;">
        {%for data in i%}
        <div class="col d-flex justify-content-around">
          <div class="card border border-dark" style="width: 18rem;height: 28rem; margin-top: 20px;margin-bottom: 20px;">
              <img src="{{data.photomy}}" class="card-img-top d-flex justify-content-around" style="width: 18rem;height: 14rem;object-fit: cover;" alt="...">
              <div class="card-body" style="width: 18rem;height: 14rem;">
              <h5 class="card-title">{{data.fname}}</h5>
              <h5 class="card-title">{{data.lname}}</h5>
              <p class="card-text">{{data.skill}}</p>
              <div class="form-group row" style="position: absolute;bottom: 10px;right: 58.67px ;">
                <div class="col"><a style="width: 66px;" href="{{url_for('user.view_port',user_port_id = data.user_port_id)}}" class="btn btn-primary">More</a></div>
                <div class="col"><a style="width: 66px;" href="{{url_for('user.form_edit',port_ids = data.port_id)}}" class="btn btn-primary">Edit</a></div>
              </div>
              
            </div>
          </div>
      </div>
      {%endfor%}
    </div>
    {%endfor%}
</div>
{%endblock%}

templates/users/login.html
{%extends "layout.html"%}
{%block content%}
<div class="container" style="width: 50%;margin-top: 15%;">

    <div class="text-center">
    <main class="form-signin w-100 m-auto">
      <form action="{{ url_for('user.do_login') }}" method="POST" class="was-validated">
        {{ form.hidden_tag() }}
        <h1 class="h3 mb-3 fw-normal">Please sign in</h1>
    
        <div class="form-floating">
          <input type="email" class="form-control is-invalid" id="email" name="email" placeholder="name@example.com">
          <label for="floatingInput">Email address</label>
        </div>
        <br>
        <div class="form-floating">
          <input type="password" class="form-control is-invalid" id="password" name="password" placeholder="Password">
          <label for="floatingPassword">Password</label>
        </div>
        <br>
        <div class="checkbox mb-3">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
      </form>
      
      {% if request.args | length > 0 %}
        <div  class="alert alert-danger" role="alert" style="margin-top: 10px;">
          <ul>
          {% for k, v in request.args.items() %}
            <li><b>{{ k }}: </b> {{ v }}</li>
          {% endfor %}
          </ul>
        </div>
      {% endif %}
    
    </main>
    </div>
    
        </div>
{%endblock%}

templates/users/regispass.html
{%extends "layout.html"%}
{%block content%}
<div class="container">

    <div class="text-center">
    <main class="form-signin w-100 m-auto">
        <img class="mb-4" src="https://www.psu.ac.th/img/logos/psu_th.png" alt="" width="150">
     
        <div  class="alert alert-success" role="alert" style="margin-top: 10px;">
          Register success
        </div>
    
    </main>
    </div>
    
        </div>
{%endblock%}

templates/users/register.html
{%extends "layout.html"%}
{%block content%}
<div class="container" style="width: 50%;margin-top: 13%;">

    <div class="text-center">
    <main class="form-signin w-100 m-auto">
      <form action="{{ url_for('user.do_register') }}" method="POST" class="was-validated">
        {{ form.hidden_tag() }}
        <h1 class="h3 mb-3 fw-normal">Please Register</h1>
        
        <div class="form-floating">
            <input type="text" class="form-control is-invalid" id="name" name="name" placeholder="Name">
            <label for="floatingInput">Name</label>
          </div>
          <br>
        <div class="form-floating">
          <input type="email" class="form-control is-invalid" id="email" name="email" placeholder="name@example.com">
          <label for="floatingInput">Email address</label>
        </div>
        <br>
        <div class="form-floating">
          <input type="password" class="form-control is-invalid" id="password" name="password" placeholder="Password">
          <label for="floatingPassword">Password</label>
        </div>
        <br>
        <div class="checkbox mb-3">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        <button class="w-100 btn btn-lg btn-primary" type="submit">Sign up</button>
      </form>
      
      {% if request.args | length > 0 %}
        <div  class="alert alert-danger" role="alert" style="margin-top: 10px;">
          <ul>
          {% for k, v in request.args.items() %}
            <li><b>{{ k }}: </b> {{ v }}</li>
          {% endfor %}
          </ul>
        </div>
      {% endif %}
    
    </main>
    </div>
    
        </div>
{%endblock%}